### ISSUE TITLE
Link to Knock

### ISSUE THREAD

**Issue by janosrusiczki** [waiting-for-dev/waiting-for-dev.github.io#3]
Hello! What!? An issue on your blog? Yeah...

Is the Knock link here intentionally wrong or is it some sort of inside joke?

https://github.com/waiting-for-dev/waiting-for-dev.github.io/blob/master/_posts/2017-01-26-a_secure_jwt_authentication_implementation_for_rack_and_rails.markdown?plain=1#L24

**Comment by waiting-for-dev** [comment]
🤣 no, that's a mistake!

**Comment by waiting-for-dev** [comment]
Fixed! Thanks for reporting. Yeah, it was surprising to see an issue on my blog 🙂
